name: push
on: push
permissions:
    contents: read
    id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.15"
      - run: go test -v -cover $(shell go list ./... | grep -v /vendor)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.15"
      - run: CGO_ENABLED=0 GOOS=linux go build -o bin/aws-sigv4-proxy
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
  docker-latest:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ECR_IAM_ROLE }}
      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
      - uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin/
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_NAME_DEFAULT }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,format=long,
      - uses: docker/build-push-action@v5
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

